'use strict';

/**
 * Manages conversation threading between viewers and the bot.
 * Tracks active conversations and provides full message history for Claude context.
 */

const pool = require('../db/pool');

/** Maximum exchanges before a conversation is considered complete. */
const MAX_EXCHANGES = 5;

/**
 * Returns the active conversation for a viewer within the current session,
 * including all previous message history. Returns null if no active
 * conversation exists or if the exchange limit has been reached.
 *
 * @param {string} viewerId  - Twitch user ID.
 * @param {number} sessionId - Current session ID.
 * @returns {Promise<{ id: number, exchange_count: number, messages: Array<{role: string, content: string}> }|null>}
 */
async function getActiveConversation(viewerId, sessionId) {
  try {
    const result = await pool.query(
      `SELECT c.id, c.exchange_count,
              COALESCE(
                json_agg(
                  json_build_object('role', cm.role, 'content', cm.content)
                  ORDER BY cm.sent_at
                ) FILTER (WHERE cm.id IS NOT NULL),
                '[]'::json
              ) AS messages
       FROM conversations c
       LEFT JOIN conversation_messages cm ON cm.conversation_id = c.id
       WHERE c.viewer_id = $1
         AND c.session_id = $2
         AND c.is_active = true
         AND c.last_message_at > NOW() - INTERVAL '5 minutes'
       GROUP BY c.id
       LIMIT 1`,
      [viewerId, sessionId],
    );

    if (result.rows.length === 0) return null;

    const convo = result.rows[0];

    if (convo.exchange_count >= MAX_EXCHANGES) {
      await closeConversation(viewerId, sessionId);
      return null;
    }

    return convo;
  } catch (err) {
    console.error('[continuity] getActiveConversation error:', err.message);
    return null;
  }
}

/**
 * Adds the latest user message and bot reply to an existing or new conversation thread.
 * Creates a new conversation record if none is active.
 *
 * @param {string} viewerId    - Twitch user ID.
 * @param {number} sessionId   - Current session ID.
 * @param {string} userMessage - The raw message sent by the viewer.
 * @param {string} botReply    - The reply generated by the bot.
 * @returns {Promise<void>}
 */
async function updateConversation(viewerId, sessionId, userMessage, botReply) {
  try {
    let convoId;

    const existing = await pool.query(
      `SELECT id FROM conversations
       WHERE viewer_id = $1 AND session_id = $2 AND is_active = true
       AND last_message_at > NOW() - INTERVAL '5 minutes'
       LIMIT 1`,
      [viewerId, sessionId],
    );

    if (existing.rows.length > 0) {
      convoId = existing.rows[0].id;
    } else {
      const inserted = await pool.query(
        `INSERT INTO conversations (viewer_id, session_id)
         VALUES ($1, $2)
         RETURNING id`,
        [viewerId, sessionId],
      );
      convoId = inserted.rows[0].id;
    }

    await pool.query(
      `INSERT INTO conversation_messages (conversation_id, role, content)
       VALUES ($1, 'user', $2)`,
      [convoId, userMessage],
    );
    await pool.query(
      `INSERT INTO conversation_messages (conversation_id, role, content)
       VALUES ($1, 'assistant', $2)`,
      [convoId, botReply],
    );
    await pool.query(
      `UPDATE conversations
       SET exchange_count = exchange_count + 1,
           last_message_at = NOW()
       WHERE id = $1`,
      [convoId],
    );
  } catch (err) {
    console.error('[continuity] updateConversation error:', err.message);
  }
}

/**
 * Marks all active conversations for a viewer in the given session as inactive.
 *
 * @param {string} viewerId  - Twitch user ID.
 * @param {number} sessionId - Current session ID.
 * @returns {Promise<void>}
 */
async function closeConversation(viewerId, sessionId) {
  try {
    await pool.query(
      `UPDATE conversations
       SET is_active = false
       WHERE viewer_id = $1 AND session_id = $2`,
      [viewerId, sessionId],
    );
  } catch (err) {
    console.error('[continuity] closeConversation error:', err.message);
  }
}

module.exports = { getActiveConversation, updateConversation, closeConversation };
